# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2861c59e02d1c6f40897af431f53100b63267c47ed19fcca5fe1e1856ccd2398ad099075e394a058897035acdc9216c57d105a61741a35e2327fc0ee23751673

test:
  secret_key_base: b52bcefab7b39d80edc5c247f6cf5c60f0705f55ed32121b48526eaba13dd97cf1f7fca35ec69f29722946c0795956c7a39fd83122cbf8fcbbea36e0dbda15aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
